const employees = [
  {
    id: 1,
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Task 1 - Employee 1",
        description: "Description 1",
        date: "2024-01-15",
        category: "Development",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        title: "Task 2 - Employee 1",
        description: "Description 2",
        date: "2024-01-16",
        category: "Testing",
      },
      {
        active: true,
        newTask: false,
        completed: true,
        failed: false,
        title: "Task 3 - Employee 1",
        description: "Description 3",
        date: "2024-01-17",
        category: "Documentation",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Task 4 - Employee 1",
        description: "Description 4",
        date: "2024-01-18",
        category: "Deployment",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Task 5 - Employee 1",
        description: "Description 5",
        date: "2024-01-19",
        category: "Design",
      },
    ],
  },
  {
    id: 2,
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Task 6 - Employee 2",
        description: "Description 6",
        date: "2024-01-22",
        category: "Email Marketing",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: true,
        title: "Task 7 - Employee 2",
        description: "Description 7",
        date: "2024-01-23",
        category: "Content Marketing",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        title: "Task 8 - Employee 2",
        description: "Description 8",
        date: "2024-01-24",
        category: "SEO",
      },
      {
        active: true,
        newTask: false,
        completed: true,
        failed: false,
        title: "Task 9 - Employee 2",
        description: "Description 9",
        date: "2024-01-25",
        category: "Analytics",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: false,
        title: "Task 10 - Employee 2",
        description: "Description 10",
        date: "2024-01-26",
        category: "Strategy",
      },
    ],
  },
  {
    id: 3,
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Task 1 - Employee 1",
        description: "Description 1",
        date: "2024-01-15",
        category: "Development",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        title: "Task 2 - Employee 1",
        description: "Description 2",
        date: "2024-01-16",
        category: "Testing",
      },
      {
        active: true,
        newTask: false,
        completed: true,
        failed: false,
        title: "Task 3 - Employee 1",
        description: "Description 3",
        date: "2024-01-17",
        category: "Documentation",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Task 4 - Employee 1",
        description: "Description 4",
        date: "2024-01-18",
        category: "Deployment",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Task 5 - Employee 1",
        description: "Description 5",
        date: "2024-01-19",
        category: "Design",
      },
    ],
  },
  {
    id: 4,
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Task 6 - Employee 1",
        description: "Description 6",
        date: "2024-01-22",
        category: "Meeting",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: true,
        title: "Task 7 - Employee 1",
        description: "Description 7",
        date: "2024-01-23",
        category: "Review",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        title: "Task 8 - Employee 1",
        description: "Description 8",
        date: "2024-01-24",
        category: "Training",
      },
      {
        active: true,
        newTask: false,
        completed: true,
        failed: false,
        title: "Task 9 - Employee 1",
        description: "Description 9",
        date: "2024-01-25",
        category: "Planning",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: false,
        title: "Task 10 - Employee 1",
        description: "Description 10",
        date: "2024-01-26",
        category: "Coding",
      },
    ],
  },
  {
    id: 5,
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Task 1 - Employee 3",
        description: "Description 1",
        date: "2024-01-15",
        category: "HR",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        title: "Task 2 - Employee 3",
        description: "Description 2",
        date: "2024-01-16",
        category: "Recruiting",
      },
      {
        active: true,
        newTask: false,
        completed: true,
        failed: false,
        title: "Task 3 - Employee 3",
        description: "Description 3",
        date: "2024-01-17",
        category: "Onboarding",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Task 4 - Employee 3",
        description: "Description 4",
        date: "2024-01-18",
        category: "Training",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Task 5 - Employee 3",
        description: "Description 5",
        date: "2024-01-19",
        category: "Performance Management",
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = ()=> {
  localStorage.setItem('employees',JSON.stringify(employees))
  localStorage.setItem('admin',JSON.stringify(admin))
}

export const getLocalStorage = ()=> {
 const employees = JSON.parse(localStorage.getItem('employees'))
 const admin = JSON.parse(localStorage.getItem('admin'))
 
 console.log(employees,admin);
 
 
}
